- src/main/scala/latis/server/Status.scala
This commit adds a case class for HAPI statuses that includes the code and the associated message as well as the set of statuses [suggested in the specification][spec].
I chose to make `Status` a case class because we can take advantage of automatic derivation of JSON encoders.
When we begin implementing the endpoints we'll be able to construct responses like this:
```scala
import io.circe.generic.auto._
import io.circe.syntax._
import org.http4s.circe._
case class SomeResponse(data: List[Int], status: Status)
Ok(SomeResponse(List(1, 2, 3), Status.`1200`).asJson)
```
Resolves #2.
[spec]: https://github.com/hapi-server/data-specification/blob/master/hapi-2.0.0/HAPI-data-access-spec-2.0.0.md#hapi-status-codes
> Add HAPI status codes

- build.sbt
- src/main/scala/latis/server/HapiService.scala
This landing page is based on the example given in the HAPI 2.0 spec.
I'm not interested in the wording at the moment unless something is terribly wrong. We will revisit the content on the page later. This is mostly about the scaffolding to get *something* there.
I went ahead and pulled in a dependency on [ScalaTags](https://www.lihaoyi.com/scalatags) now rather than wait until we're actually dynamically generating content.
Resolves #3.
> Add simple landing page

- build.sbt
- src/main/scala/latis/server/CapabilitiesService.scala
- src/main/scala/latis/server/HapiServer.scala
- src/main/scala/latis/server/Status.scala
- src/test/scala/latis/server/CapabilitiesServiceSpec.scala
I've implemented the [capabilities endpoint](https://github.com/hapi-server/data-specification/blob/master/hapi-2.0.0/HAPI-data-access-spec-2.0.0.md#capabilities) with the assumption that we will support all of the standard HAPI outputs.
I imagine in the future we might revisit this so the list of outputs is dynamically generated and includes custom output formats. (Though it isn't clear to me how the custom formats are expected to behave.)
I've also left these two commits separate for the purpose of this review:
- [6a014c0](https://github.com/lasp/latis-hapi/pull/21/commits/6a014c0f107f28e25d47268224779fe8da639d3a) : tests implemented with [uTest](https://github.com/lihaoyi/utest)
- [38fec45](https://github.com/lasp/latis-hapi/pull/21/commits/38fec45654ae505d1a7f988048eff5cf31fb6f6f) : …
> Implement capabilities endpoint

- src/main/scala/latis/server/CatalogService.scala
- src/test/scala/latis/server/CatalogServiceSpec.scala
I've added the `Catalog` and `Dataset` types (and their JSON encoders) for responses from the `catalog` endpoint.
I recognize we have another (much more important) `Dataset` type, but I think after #17 the package structure will change enough to differentiate them even more.
Resolves #6.
> Add types for catalog endpoint responses

- src/main/scala/latis/server/DataService.scala
- src/test/scala/latis/server/DataServiceSpec.scala
The main thrust of this was adding the `DataRequest` type.
On top of that, I've added instances of the `QueryParamDecoder` typeclass for some of the things in the `DataRequest` object so we can pull them from queries and see how parsing the queries behaves. I don't think any of the behavior with respect to the queries goes against the spec, but the behavior could be improved. I'll make other tickets for that.
There's a lot of refactoring that will need to be done as the other endpoints are fleshed out, so the places things are now will likely change to make more sense. I just need them here now.
Resolves #9.
> Add types for 'data' requests

- src/main/scala/latis/server/InfoService.scala
We will need to revisit where these types live after this is merged and the project restructuring is done.
There are also some things that should be done to make these types better capture the requirements in the spec. For instance, `Bin` types cannot have both the `ranges` and `centers` fields defined. It would be good to enforce this somehow.
Resolves #8.
> Add request, response types for info requests

- src/main/scala/lasp/hapi/util/Time.scala
- src/test/scala/lasp/hapi/util/TimeSpec.scala
This uses the `java.time` API to parse HAPI time strings.
See [Representation of Time](https://github.com/hapi-server/data-specification/blob/master/hapi-2.0.0/HAPI-data-access-spec-2.0.0.md#representation-of-time) in the HAPI spec.
See #26.
> Add HAPI time string parser

- src/main/scala/lasp/hapi/server/HapiServer.scala
- src/main/scala/lasp/hapi/service/CapabilitiesService.scala
- src/main/scala/lasp/hapi/service/CatalogService.scala
- src/main/scala/lasp/hapi/service/DataService.scala
- src/main/scala/lasp/hapi/service/HapiService.scala
- src/main/scala/lasp/hapi/service/InfoService.scala
- src/main/scala/lasp/hapi/service/LandingPageService.scala
- src/test/scala/lasp/hapi/service/CapabilitiesServiceSpec.scala
Stuff in `lasp.hapi.service` will eventually become its own project that can be used in other projects, and this is the first step towards that.
`HapiService` is intended to be a self-contained HAPI service that has the four HAPI endpoints properly routed and configured. Ideally, one could create an instance of `HapiService` and `mount` it in their server (with the proper configuration) to add a HAPI service to their server.
Prior to these changes, the routing and configuration was handled by `HapiServer` (the implementation of this specific standalone HAPI server) even though any server providing a HAPI service would need to do the same things.
> Make HAPI service more suitable for standalone use

- src/main/scala/lasp/hapi/service/DataRequest.scala
- src/main/scala/lasp/hapi/service/DataService.scala
- src/main/scala/lasp/hapi/service/Format.scala
- src/main/scala/lasp/hapi/service/Include.scala
- src/main/scala/lasp/hapi/service/QueryDecoders.scala
- src/test/scala/lasp/hapi/service/DataServiceSpec.scala
I've used the parser added in #33 to validate time strings given in queries. As I wrote the code to do the validation, I figured I might as well do the whole thing, so now the entire query is validated and we actually end up constructing the `DataRequest` object that will eventually be used to construct a response.
Here's where we are now:
- If the query is invalid, we return the appropriate HAPI status.
- See the tests for examples of this.
- If the query is valid, we construct the `DataRequest` object, throw it away, and give the `"Hello from HAPI!"` response.
Resolves #26 and resolves #28.
> Construct DataRequest object from query

- build.sbt
- src/main/scala/lasp/hapi/server/HapiServer.scala
- src/main/scala/lasp/hapi/service/CatalogAlgebra.scala
- src/main/scala/lasp/hapi/service/CatalogService.scala
- src/main/scala/lasp/hapi/service/HapiInterpreter.scala
- src/main/scala/lasp/hapi/service/HapiService.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Interpreter.scala
**Overview of changes**
- Add a source dependency on LaTiS 2.
- We are depending on a particular commit from LaTiS 2 on GitHub.
- After the tag for the next release is pushed I'll update the commit here to point to that tag. Ideally we'll just depend on tagged releases of LaTiS 2.
- Define `CatalogAlgebra`.
- This is an algebra in the [tagless final](https://www.beyondthelines.net/programming/introduction-to-tagless-final/) sense.
- In short, `CatalogAlgebra` is a typeclass that defines the operations one can do to the catalog. In our case, the only operation is to get the catalog.
- "Interpreters" of this algebra implement the operation.
- Implement the `catalog` endpoint in terms of `CatalogAlgebra`.
- Rather than relying on a concrete implementation, we can rely on the abstract …
> Read a LaTiS 2 catalog

- README.md
- build.sbt
- src/main/resources/reference.conf
- src/main/scala/lasp/hapi/server/HapiServer.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Interpreter.scala
- src/main/scala/lasp/hapi/util/HapiConfig.scala
After looking at a few options I've settled on giving [PureConfig][pc] a shot. It wraps the [Lightbend Config][lc] library with some nice things and has [support for cats][pc-cats] and [cats-effect][pc-cats-effect].
What I like most about PureConfig is that it will read the configuration into a case class. This way your configuration is a value that you could generate by hand rather than something magic that can only come from a configuration file or system properties. `HapiConfig` is the case class I've introduced to hold the configuration.
Closes #14.
[hocon]: https://github.com/lightbend/config/blob/master/HOCON.md
[lc]: https://github.com/lightbend/config
[pc]: https://github.com/pureconfig/pureconfig
[pc-cats]: https://github.com/pureconfig/pureconfig/tree/master/modules/cats …
> Set up configuration

- src/main/scala/lasp/hapi/service/CapabilitiesService.scala
- src/main/scala/lasp/hapi/service/DataAlgebra.scala
- src/main/scala/lasp/hapi/service/DataService.scala
- src/main/scala/lasp/hapi/service/Format.scala
- src/main/scala/lasp/hapi/service/HapiInterpreter.scala
- src/main/scala/lasp/hapi/service/HapiService.scala
- src/main/scala/lasp/hapi/service/Parameter.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Interpreter.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Util.scala
- src/main/scala/lasp/hapi/util/Time.scala
- src/test/scala/lasp/hapi/service/CapabilitiesServiceSpec.scala
- src/test/scala/lasp/hapi/service/DataServiceSpec.scala
These commits add the algebra and interpreters for `data` requests.
In particular, look at how I implemented the algebra in `Latis2Interpreter` and let me know if there's a better way to do the things I've done. I'll need to revisit later and work on patching things up so we return useful errors when things go wrong on the LaTiS side.
I believe the same limitations that applied to `info` requests (#10, #39) apply here.
I've restricted the output to CSV only (the minimum required) to make life easier for now. I've also just implemented a really dumb CSV writer because the dataset shapes we're supporting now are simple.
Closes #11.
> Implement data response

- build.sbt
- src/main/scala/lasp/hapi/service/InfoResponse.scala
- src/main/scala/lasp/hapi/service/Metadata.scala
- src/main/scala/lasp/hapi/service/Parameter.scala
This commit cleans up our JSON responses by removing unset optional parameters from the response.
Many parts of the info response are optional, and the default encoders translate `None` into `null`, so we had large JSON objects full of `null`s. The new encoders introduced by this commit remove keys with null values, with the exception of "`fill` which is required to be present even when null.
I've also had to explicitly rename `dType` to `type` because the derived encoder will use the name of the parameter from the case class.
Closes #45.
> Clean up JSON responses

- README.md
- build.sbt
- src/main/scala/lasp/hapi/server/HapiServer.scala
Most of the changes required to make LaTiS 2 the default were finding the appropriate classpath to copy into the Docker image.
The confusing part was the fact that we're depending on LaTiS 2 as a source dependency. Apparently we can get the JAR through `internalDependencyAsJars`, so I just add that to the things being copied into the image.
Closes #43.
> Make LaTiS 2 the default interpreter

- src/main/scala/lasp/hapi/service/Bin.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Interpreter.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Util.scala
- src/test/scala/lasp/hapi/service/BinSpec.scala
This PR adds support for 2D datasets to the LaTiS 2 interpreter. Because we're now using `Bin` objects I've also cleaned up the JSON we generate from them.
Check out the LaTiS code to make sure I'm not doing anything crazy.
Closes #52.
> Support datasets with a second dimension

- src/main/scala/lasp/hapi/service/TimeStampLocation.scala
- src/main/scala/lasp/hapi/service/latis2/Latis2Util.scala
The commit adds support for the optional metadata items.
See the [spec][info] for descriptions of each item.
I've kept most of the names as-is because they'll be easy to change later. If you (@dlindhol) know of a better name, let me know and I'll change it.
One question I have is in regards to the cadence and time stamp location: should those be on the dataset as a whole, or on the time variable? (Right now I have them on the dataset because it was where everything else was.)
Closes #53.
[info]: https://github.com/hapi-server/data-specification/blob/master/hapi-2.0.0/HAPI-data-access-spec-2.0.0.md#info
> Support optional metadata

- build.sbt
- src/main/resources/logback.xml
- src/main/scala/lasp/hapi/service/DataService.scala
- src/main/scala/lasp/hapi/service/HapiService.scala
- src/main/scala/lasp/hapi/service/InfoService.scala
I've wrapped the HAPI service in the `http4s` logging middleware, which logs requests and responses. Because some of our responses are data, I've disabled logging the bodies of responses. Instead, when we generate a HAPI error, I log the associated error message.
Blaze will already log exceptions that occur during the process of responding to a request.
There is certainly more work to be done here. I'm rethinking how we handle errors, and that will impact how we log them. This is probably good enough for now.
Closes #60.
> Improve logging

- build.sbt
- project/build.properties
- src/main/scala/latis/ops/ToHapiTime.scala
- src/main/scala/latis/service/hapi/HapiService.scala
- src/main/scala/latis/service/hapi/InfoError.scala
- src/main/scala/latis/service/hapi/Latis3Interpreter.scala
- src/main/scala/latis/util/HapiUtils.scala
This PR brings a number of fixes and dependency updates to make `hapi-server` compatible with the latest `latis3` again.
Note that I'm waiting on the [related latis3-hapi PR](https://github.com/latis-data/latis3-hapi/pull/15) to get merged before I can point this `build.sbt` at it.
Like the other PR, I stopped short of making the whole repo idiomatic; I just made it work.
> Revive hapi-server

- build.sbt
- src/main/scala/latis/service/hapi/DataService.scala
- src/main/scala/latis/service/hapi/Format.scala
As per issue @ https://github.com/lasp/hapi-server/issues/76 from Chris: 
"Rather than taking a string argument, change to a sum type with CSV, binary, and JSON constructors."
> Format sum type

- build.sbt
- src/main/scala/latis/ops/ToHapiTime.scala
- src/test/scala/latis/service/hapi/BinSpec.scala
- src/test/scala/latis/service/hapi/CapabilitiesServiceSpec.scala
- src/test/scala/latis/service/hapi/CatalogServiceSpec.scala
- src/test/scala/latis/service/hapi/DataServiceSpec.scala
- src/test/scala/latis/service/hapi/TimeSpec.scala
- src/test/scala/latis/service/hapi/ToHapiTimeSpec.scala
Moves the mandatory setting of the size metadata for Time(s) to ToHapiTime, with constant value 24 because that is the known size of the always-used format: "yyyy-mm-ddThh:mm:ss.sssZ"
This currently passes all existing tests, including my recent DataService tests that use a Time domain but now no longer use directly-set size metadata for it. I am conflicted on whether more tests are needed....
> HAPI-73 set Time metadata size in ToHapiTime

- src/main/scala/latis/service/hapi/HapiService.scala
- src/main/scala/latis/service/hapi/LandingPageService.scala
- src/test/scala/latis/service/hapi/LandingPageServiceSpec.scala
Adds a table with the catalog of datasets to the landing page, with links to the relevant info requests. I am definitely open to making stylistic changes if desired.
> Hapi 77 Landing Page Catalog

- build.sbt
- src/main/scala/latis/ops/ConvertHapiTypes.scala
- src/main/scala/latis/service/hapi/HapiService.scala
- src/main/scala/latis/service/hapi/Latis3Interpreter.scala
- src/main/scala/latis/service/hapi/Parameter.scala
This updates what datasets make it into the HAPI catalog. The filter changes include:
- Look for `temporalCoverage` in the dataset metadata instead of using `coverage` from the time variable. The latter requires a precise definition to support index math (e.g. netCDF subsetting) while the former supports the nominal coverage required by HAPI.
- Support `short` and `float` types by converting them as needed for binary output. They should otherwise be fine for CSV and JSON output (rather than add noisy extra floating point precision). We can consider adding others as needed, though I opted for safe type conversions. Note that longs will not be supported in the *range* but times as longs will still be supported since they will get converted to ISO anyway.
- Remove requirement for `units` to …
> Update HAPI Catalog Filter

- build.sbt
- src/test/resources/logback-test.xml
Server projects that depend on this otherwise risk loading the wrong log configuration. This preserves the ability to manage/silence logs during testing.
> Remove main logback config
